language: python

jobs:
  include:
    - name: "Test a standard example"
      python: 3.7
      env: CALC_ENTRY=
    - name: "Test the fix for the AD4_parameters.dat"
      python: 3.7
      env: CALC_ENTRY="CC(C[C@@H](B(O)O)NC(=O)[C@@H](NC(=O)c1cnccn1)Cc1ccccc1)C DB-84"
    - name: "Test the fix for the 'unknown W# atom type' issue"
      python: 3.7
      env: CALC_ENTRY="Nc1nc2NC3OC4COP(=O)([O-])O[Mg]OP(=O)(OCC5C6=C(S[W]7(SC(=C4S7)C3Nc2c(=O)[nH]1)S6)C1Nc2c(NC1O5)nc([nH]c2=O)N)[O-] DB-1573"
    - name: "Test the missing Cr atom from AD4_parameters.dat"
      python: 3.7
      env: CALC_ENTRY="[O-][51Cr](=O)(=O)[O-] DB-10072"

before_install:
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        arch="Linux"
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
        arch="MacOSX"
    else
        echo "Unknown arch $TRAVIS_OS_NAME"
        exit 1
    fi
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-${arch}-x86_64.sh -O miniconda.sh
    chmod +x miniconda.sh
    ./miniconda.sh -b -p ~/mc
    source ~/mc/etc/profile.d/conda.sh
    conda update conda --yes

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -y -n covid19 -c nsls2forge -c conda-forge python=$TRAVIS_PYTHON_VERSION openbabel autodock
  - conda activate covid19
  # The following step needs to be performed separately as it installs
  # Python 2.5 and replaces environment's python executable (we expect it), so
  # that the 'pythonsh' tool works correctly. For other purposes, 'python3'
  # should be used.
  - conda install -y -c nsls2forge mgltools
  - env | sort -u
  - conda list
  - pip list
  - python -VV
  - python3 -VV
  - obabel -V
  - ulimit -s unlimited && autodock4 --version && autogrid4 --version
  - pythonsh --help

script:
  - |
    set -e
    # Unlimit stack size to avoid autodock crashes.
    ulimit -s unlimited
    cd ProcessingScripts/

    if [ ! -z "$CALC_ENTRY" ]; then
        echo "$CALC_ENTRY" > ena+db-small.can
    fi

    echo -e "The contents of 'ena+db-small.can':"
    python3 -c "print('=' * 80)"
    cat ena+db-small.can
    python3 -c "print('=' * 80, '\n')"

    ./example.sh
