language: python

jobs:
  include:
    - python: 3.6
    - python: 3.7

before_install:
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        arch="Linux"
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
        arch="MacOSX"
    else
        echo "Unknown arch $TRAVIS_OS_NAME"
        exit 1
    fi
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-${arch}-x86_64.sh -O miniconda.sh
    chmod +x miniconda.sh
    ./miniconda.sh -b -p ~/mc
    source ~/mc/etc/profile.d/conda.sh
    conda update conda --yes

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -y -n covid19 -c nsls2forge -c conda-forge python=$TRAVIS_PYTHON_VERSION openbabel autodock
  - conda activate covid19
  - conda install -y -c nsls2forge mgltools
  - conda list
  - pip list
  - python -VV
  - python3 -VV

script:
  - |
    set -e
    ulimit -s unlimited
    cd ProcessingScripts/
    # Test a standard example:
    ./example.sh

    # Test the fix for the AD4_parameters.dat:
    echo "CC(C[C@@H](B(O)O)NC(=O)[C@@H](NC(=O)c1cnccn1)Cc1ccccc1)C DB-84" > ena+db-small.can
    ./example.sh

    # Test the fix for the "unknown W# atom type" issue:
    echo "Nc1nc2NC3OC4COP(=O)([O-])O[Mg]OP(=O)(OCC5C6=C(S[W]7(SC(=C4S7)C3Nc2c(=O)[nH]1)S6)C1Nc2c(NC1O5)nc([nH]c2=O)N)[O-] DB-1573" > ena+db-small.can
    ./example.sh
